#contentDir = "content"
staticDir = "static"
#uglyurls = true 
baseURL = "http://zhangeamon.top"
languageCode = "zh-CN"
title = "Let's go ğŸŒ ğŸŒ ğŸŒ"
theme = "maupassant-hugo"
googleAnalytics = ""  # UA-XXXXXXXX-X

## ä¿æŒåˆ†ç±»çš„åŸå§‹åå­—ï¼ˆfalseä¼šåšè½¬å°å†™å¤„ç†ï¼‰
preserveTaxonomyNames = true
## æ˜¯å¦ç¦æ­¢URL Pathè½¬å°å†™
disablePathToLower = true

hasCJKLanguage = true
summaryLength = 140

#disqusShortname = "yourdiscussshortname"  ## æ˜¯å¦å¼€å¯disqusè¯„è®ºï¼Œä¸è¦å’ŒutterancåŒæ—¶å¼€å¯

[author]
  name = "Eamon"

[params]
  author = "Eamon"
  subtitle = "Let's build our own cloud native together  "
  linkGithub = "https://github.com/eamonzhang"
  keywords = "postgres ã€pythonã€pg ã€linix ã€dockerã€ kubernetesã€ cloudã€hadoopã€promethues "
  description = "python è½¯ä»¶æ¶æ„ç­‰"
  busuanzi = false #å¯ç”¨ä¸ç®—å­ç½‘é¡µç»Ÿè®¡
  googleAd = ""  #ca-pub-xxxxxxxxxxxxxx
  localSearch = true # å¯ç”¨æœ¬åœ°æœç´¢
  # è¿™é‡Œæˆ‘å­˜æ”¾åœ¨äº†ä¸»é¢˜çš„staticæ–‡ä»¶å¤¹é‡Œï¼Œæ ¹ç›®å½•çš„ä¼¼ä¹ä¹Ÿå¯ä»¥
  customCSS = ['douban.css', 'other.css']
  # if ['custom.css'], load '/static/css/custom.css' file
  customJS = ['douban.js']
  # if ['custom.js'], load '/static/js/custom.js' file

  # å…¨å±€å¼€å…³ï¼Œä½ ä¹Ÿå¯ä»¥åœ¨æ¯ä¸€ç¯‡å†…å®¹çš„ front matter ä¸­é’ˆå¯¹å•ç¯‡å†…å®¹å…³é—­æˆ–å¼€å¯æŸäº›åŠŸèƒ½
  toc = false  # æ˜¯å¦å¼€å¯ç›®å½•

## å‹æƒ…é“¾æ¥ï¼Œå¯ä»¥å¤šä¸ª

[[params.links]]
  title = "å†å²åšå®¢"
  name = "å†å²åšå®¢"
  url = "http://www.cnblogs.com/zhangeamon"

#[[params.links]]
#  title = "Android Gradleæƒå¨æŒ‡å—"
#  name = "Android Gradleæƒå¨æŒ‡å—"
#  url = "http://yuedu.baidu.com/ebook/14a722970740be1e640e9a3e"

## ä¾§è¾¹æ å¹¿å‘Šä½
#[[params.ads]]
#  title = "ã€2019åŒ12ã€‘ALL IN CLoud ä½è‡³1æŠ˜"
#  url = "https://www.aliyun.com/minisite/goods?userCode=jdg9oj97&share_source=copy_link"
#  img = "https://img.alicdn.com/tfs/TB1_rYHo7P2gK0jSZPxXXacQpXa-690-388.jpg"
#[[params.ads]]
#  title = "åŠ©åŠ›äº§ä¸šæ™ºæ…§å‡çº§ï¼Œäº‘æœåŠ¡å™¨é¦–å¹´88å…ƒèµ·ï¼Œæ›´æœ‰åƒå…ƒä»£é‡‘åˆ¸ç¤¼åŒ…å…è´¹é¢†ï¼"
#  url = "https://cloud.tencent.com/act/cps/redirect?redirect=1048&cps_key=14ff722692ac784fa8c3301c8c28d924&from=console"
#  img = "https://upload-dianshi-1255598498.file.myqcloud.com/345-7c71532bd4935fbdd9a67c1a71e577b1767b805c.200%E7%89%88%E6%9C%ACB.jpg"
#[[params.ads]]
#  title = "ã€æ¸ é“ä¸“äº«ä½æŠ˜æ‰£ã€‘11æœˆç‰¹æƒ  é™æ—¶2æŠ˜"
#  url = "https://www.aliyun.com/acts/limit-buy?userCode=jdg9oj97"
#  img = "https://img.alicdn.com/tfs/TB1hblJl7Y2gK0jSZFgXXc5OFXa-750-400.jpg"

## é…ç½® utterancè¯„è®º,æ•™ç¨‹å‚è€ƒ https://utteranc.es/
[params.utteranc]
  enable = true 
  repo = "your github repo" ##æ¢æˆè‡ªå·±å¾—
  issueTerm = "pathname"
  theme = "github-light"

## å¼€å¯ç‰ˆæƒå£°æ˜ï¼Œåè®®åå­—å’Œé“¾æ¥éƒ½å¯ä»¥æ¢
#[params.cc]
#    name = "å£°æ˜åè®®"
#    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

## é…ç½®ä»£ç é«˜äº®
[markup]
  [markup.highlight]
    lineNos = true
    style = "github"

## é…ç½®ç½‘ç«™èœå•

[menu]

  [[menu.main]]
    identifier = "postgresql"
    name = "Postgres"
    url = "postgresql"
    weight = 3

  [[menu.main]]
    identifier = "archives"
    name = "å½’æ¡£"
    url = "archives"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "å…³äº"
    url = "about/me"
    weight = 20
  
  [[menu.main]]
    identifier = "linux"
    name = "Linux"
    url = "linux"
    weight = 5
